package com.kiranaservice.kiranaServiceNew.models;

import lombok.Getter;
import lombok.Setter;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;

import java.time.LocalDateTime;

@Document(collection = "transaction")
@Getter
@Setter
public class Transaction {
    //This system is basically for multiple kirana stores ( having unique store id through which they can per
    //form different transaction in the system
    /** This is the schema on real life based transaction occuring in Kirana stores helping the use case to store in DB
     * kiranaStoreId is unique for every store
     * transactionId is something which is unique for every transaction generated by us, for further use by store.
     * transactionType - CREDIT/DEBIT
     * timestamp - at which the transaction occured
     */

    @Id
    private String transactionId;
    private String kiranaStoreId;
    private Double originalAmount;
    private String originalCurrency;
    private Double convertedAmountInINR;
    private String transactionType;
    private LocalDateTime timestamp;
}
